name: monitor-p1000
on:
  schedule:
  - cron: "0/10 * * * *"
  push:
    branches: [master]
jobs:
  monitor-p1000:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: node monitor-p1000.js
      env:
        LUOGU_UID: ${{ secrets.LUOGU_UID }}
        LUOGU_CLIENT_ID: ${{ secrets.LUOGU_CLIENT_ID }}
        GIST_ID: e1ef4f33f55855d99524758022dc30ac
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
